spring:
  datasource:
    name: MyDB
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=DeXing
    username: sa
    password: 1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  thymeleaf:
    enabled: true
    encoding: utf-8
    prefix: classpath:/templates/
    cache: false
    mode: HTML
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dx.employee.pojo
